version: "3.8"
services:
  rust-app:
    image: rust:latest
    container_name: rust-app
    working_dir: /app
    ports:
      - "4004:4004"
    command: >
      sh -c "if [ -d /app/.git ]; then \
        cd /app && git pull; \
      else \
        git clone --branch main https://github.com/kubusss77/mchess-rust-coolify.git /app; \
      fi && \
      cd /app && \
      cargo build --release && \
      cargo run --release"